#!/usr/bin/env bash
#Script that transfers a file from our client to a server

# Check if all required parameters are provided
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key_path="$4"

# Disable strict host key checking
export SSHPASS="-o StrictHostKeyChecking=no"

# Transfer the file using scp
scp -i "$ssh_key_path" "$file_path" "$username@$server_ip:~/"

# Check if scp command was successful
if [ "$?" -eq 0 ]; then
    echo "File transfer complete."
else
    echo "Error occurred during file transfer."
fi
