#!/usr/bin/env bash
# configures an Nginx server so that /redirect_me redirects to another page.
# The redirection is configured as a "301 Moved Permanently"
# Includes a custom 404 page containing "Ceci n'est pas une page".

# Update package lists
sudo apt-get update -y

# Install Nginx
sudo apt-get install -y nginx

# Configure Nginx
cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    location / {
        return 200 "Hello World!\n";
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        internal;
        return 404 "Ceci n'est pas une page";
    }
}
EOF

# Restart Nginx
service nginx restart
